### ISSUE TITLE
Snake Example: The apple only spawns on the left side of the screen

### ISSUE THREAD

**Issue by nellfs** [ricardoalcantara/rust-wgpu-breakout#7]
After the 'Frute' is eaten it should appear in a random place on the screen, but it only appears on the left side (x=0)

**Comment by ricardoalcantara** [comment]
My bad https://github.com/ricardoalcantara/breakout-engine/blob/main/examples/snake.rs#L99

**Comment by ricardoalcantara** [comment]
fixed
